// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxFBLWPnEtN3SEqZl-qAkar971WSoHC7U',
    appId: '1:935273134971:web:2adbffbe601c4990b69bde',
    messagingSenderId: '935273134971',
    projectId: 'ease-mvp',
    authDomain: 'ease-mvp.firebaseapp.com',
    storageBucket: 'ease-mvp.appspot.com',
    measurementId: 'G-7WH0TJHGVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2M5VQCl9wGteRZ6vs0nUAOLEtl-qOHo',
    appId: '1:935273134971:android:242a724e91f64bfbb69bde',
    messagingSenderId: '935273134971',
    projectId: 'ease-mvp',
    storageBucket: 'ease-mvp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuSXAR-XpsLHxefotRCi6xsI0lVqHkEkM',
    appId: '1:935273134971:ios:cf50da81bc040f6bb69bde',
    messagingSenderId: '935273134971',
    projectId: 'ease-mvp',
    storageBucket: 'ease-mvp.appspot.com',
    iosBundleId: 'com.atketan.ease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuSXAR-XpsLHxefotRCi6xsI0lVqHkEkM',
    appId: '1:935273134971:ios:2e84500aab75e56db69bde',
    messagingSenderId: '935273134971',
    projectId: 'ease-mvp',
    storageBucket: 'ease-mvp.appspot.com',
    iosBundleId: 'com.example.easeMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxFBLWPnEtN3SEqZl-qAkar971WSoHC7U',
    appId: '1:935273134971:web:9f8fcf763e938ea8b69bde',
    messagingSenderId: '935273134971',
    projectId: 'ease-mvp',
    authDomain: 'ease-mvp.firebaseapp.com',
    storageBucket: 'ease-mvp.appspot.com',
    measurementId: 'G-CKEDR8DRFD',
  );

}