class Expense {
  int? id;
  String? expenseId; // Firestore document ID
  String expenseNumber; // to be generated by the system, could be a custom alphanumeric series
  String? notes;
  String? name; // category name - to avoid calling categories collection
  String? categoryId;
  double amount;
  double totalPaid;
  String status; // paid, unpaid, partially paid
  DateTime createdAt;
  DateTime updatedAt;

  Expense({
    this.id,
    this.expenseId,
    required this.expenseNumber,
    required this.name,
    this.notes,
    this.categoryId,
    required this.amount,
    required this.totalPaid,
    required this.status,
    required this.createdAt,
    required this.updatedAt,
  });

  factory Expense.fromJSON(Map<String, dynamic> json) {
    return Expense(
      id: json['id'],
      expenseId: json['expense_id'],
      expenseNumber: json['expense_number'],
      name: json['name'],
      notes: json['notes'],
      categoryId: json['category_id'],
      amount: json['amount'],
      totalPaid: json['total_paid'],
      status: json['status'],
      createdAt: DateTime.parse(json['created_at']),
      updatedAt: DateTime.parse(json['updated_at']),
    );
  }

  Map<String, dynamic> toJSON() {
    return {
      'id': id,
      'expense_id': expenseId,
      'expense_number': expenseNumber,
      'name': name,
      'notes': notes,
      'category_id': categoryId,
      'amount': amount,
      'total_paid': totalPaid,
      'status': status,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}
